### ISSUE TITLE
Anropa dokarkiv direkt istället för att gå via api-gw

### ISSUE THREAD

**Issue by albrektsson** [navikt/omsorgspenger-journalforing#9]
> Ny ingress for dokarkiv slik at denne kan nås fra GCP:
> https://dokarkiv.dev-fss-pub.nais.io - Går mot joark i Q1. Whitelisted. Ønsker at teams med GCP app og som bruker dokarkiv kan teste dette.

**Comment by fraadsbrandth** [comment]
Fikset i #10
